
package com.lshop.ws.web.bz.order;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "BzExpressServiceService", targetNamespace = "http://service.webservice.datainterface.bz.gv.com/", wsdlLocation = "http://10.0.2.80:8080/gv_bz/webservice/BzExpressService?wsdl")
public class BzExpressServiceService
    extends Service
{

    private final static URL BZEXPRESSSERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.lshop.ws.web.bz.order.BzExpressServiceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.lshop.ws.web.bz.order.BzExpressServiceService.class.getResource(".");
            url = new URL(baseUrl, "http://10.0.2.80:8080/gv_bz/webservice/BzExpressService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://10.0.2.80:8080/gv_bz/webservice/BzExpressService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        BZEXPRESSSERVICESERVICE_WSDL_LOCATION = url;
    }

    public BzExpressServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BzExpressServiceService() {
        super(BZEXPRESSSERVICESERVICE_WSDL_LOCATION, new QName("http://service.webservice.datainterface.bz.gv.com/", "BzExpressServiceService"));
    }

    /**
     * 
     * @return
     *     returns BzExpressService
     */
    @WebEndpoint(name = "BzExpressServicePort")
    public BzExpressService getBzExpressServicePort() {
        return super.getPort(new QName("http://service.webservice.datainterface.bz.gv.com/", "BzExpressServicePort"), BzExpressService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BzExpressService
     */
    @WebEndpoint(name = "BzExpressServicePort")
    public BzExpressService getBzExpressServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.webservice.datainterface.bz.gv.com/", "BzExpressServicePort"), BzExpressService.class, features);
    }

}
