
package com.lshop.ws.web.bz.order;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "BzExpressService", targetNamespace = "http://service.webservice.datainterface.bz.gv.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BzExpressService {


    /**
     * 
     * @param code
     * @return
     *     returns com.lshop.ws.web.bz.order.ExpressResponse
     */
    @WebMethod
    @WebResult(name = "expressResponse", partName = "expressResponse")
    public ExpressResponse findLogisticsByCode(
        @WebParam(name = "code", partName = "code")
        String code);

    /**
     * 
     * @param startDate
     * @param endDate
     * @return
     *     returns com.lshop.ws.web.bz.order.MultiExpressResponse
     */
    @WebMethod
    @WebResult(name = "multiExpressResponse", partName = "multiExpressResponse")
    public MultiExpressResponse findLogisticsByDate(
        @WebParam(name = "startDate", partName = "startDate")
        String startDate,
        @WebParam(name = "endDate", partName = "endDate")
        String endDate);

}
